        'app.log.hook'         => true,
        #'app.log.query'        => true,
        #'app.log.requestData'  => true,
        #'app.log.translations' => true,
        #'app.log.apiCache'     => true,
        #'app.log.path'         => '/dados/mapas/logs/',
